USE [master]
GO

/****** Object:  Database [CompanyDb]    Script Date: 29-03-2020 14:08:57 ******/
CREATE DATABASE [CompanyDb] ON  PRIMARY 
( NAME = N'CompanyDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\CompanyDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CompanyDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\CompanyDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CompanyDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CompanyDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CompanyDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CompanyDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CompanyDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CompanyDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CompanyDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CompanyDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CompanyDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CompanyDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CompanyDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CompanyDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CompanyDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CompanyDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CompanyDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CompanyDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CompanyDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CompanyDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CompanyDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CompanyDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CompanyDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CompanyDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CompanyDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CompanyDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CompanyDb] SET  MULTI_USER 
GO

ALTER DATABASE [CompanyDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CompanyDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CompanyDb] SET  READ_WRITE 
GO

