USE [master]
GO

/****** Object:  Database [HospitalDb]    Script Date: 25-03-2020 20:48:50 ******/
CREATE DATABASE [HospitalDb] ON  PRIMARY 
( NAME = N'HospitalDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\HospitalDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HospitalDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\HospitalDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HospitalDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HospitalDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HospitalDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HospitalDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HospitalDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HospitalDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [HospitalDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HospitalDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HospitalDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HospitalDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HospitalDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HospitalDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HospitalDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HospitalDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HospitalDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HospitalDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HospitalDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HospitalDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HospitalDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HospitalDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HospitalDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HospitalDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HospitalDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HospitalDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HospitalDb] SET  MULTI_USER 
GO

ALTER DATABASE [HospitalDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HospitalDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HospitalDb] SET  READ_WRITE 
GO

