USE [master]
GO

/****** Object:  Database [ToyDb]    Script Date: 26-03-2020 14:41:47 ******/
CREATE DATABASE [ToyDb] ON  PRIMARY 
( NAME = N'ToyDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ToyDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ToyDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ToyDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ToyDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ToyDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ToyDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ToyDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ToyDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ToyDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [ToyDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ToyDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ToyDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ToyDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ToyDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ToyDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ToyDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ToyDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ToyDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ToyDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ToyDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ToyDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ToyDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ToyDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ToyDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ToyDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ToyDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ToyDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ToyDb] SET  MULTI_USER 
GO

ALTER DATABASE [ToyDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ToyDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ToyDb] SET  READ_WRITE 
GO

